
dataset_cerra: "/projects/0/prjs0951/MASK_GNN_DATA/CERRA_interpolated_300x300"
dataset_era5: null #"/projects/0/prjs0951/MASK_GNN_DATA/ERA5_60_n2_40_18"
graph: "hierarchical_highRes_only"

run_name: KL_75_HighResOnly_20

model: "graph_efm"
subset_ds: 0
seed: 42
n_workers: 8
epochs: 200
batch_size: 16

load: null
restore_opt: 0
precision: "16-mixed"

hidden_dim: 64
latent_dim: null
hidden_layers: 1
processor_layers: 4
encoder_processor_layers: 2
prior_processor_layers: 2
mesh_aggr: "sum"
output_std: 0
prior_dist: "isotropic"
learn_prior: 1
vertical_propnets: 0

loss: "mse"
step_length: 3
lr: 0.001
val_interval: 1

eval: null
mask_ratio: 0.75
masking_block_size: 20
wandb_project: neural-lam-HighResOnly

kl_term: 1
kl_beta: 0.01
