
dataset_cerra: "/projects/0/prjs0951/MASK_GNN_DATA/CERRA_interpolated_300x300"
dataset_era5: "/projects/0/prjs0951/MASK_GNN_DATA/ERA5_60_n2_40_18"
graph: "hierarchical_HighLow_res"

model: "graph_efm"
subset_ds: 0
seed: 42
n_workers: 8
epochs: 200
batch_size: 8

load: "saved_models/graph_efm-4x64-03_04_19-3294/min_val_loss.ckpt"
restore_opt: 0
precision: "16-mixed"

hidden_dim: 64
latent_dim: null
hidden_layers: 1
processor_layers: 4
encoder_processor_layers: 2
prior_processor_layers: 2
mesh_aggr: "sum"
output_std: 0
prior_dist: "isotropic"
learn_prior: 1
vertical_propnets: 0

loss: "mse"
step_length: 3
lr: 0.001
val_interval: 1

eval: val
mask_ratio: 1.0
masking_block_size: 50
wandb_project: null #neural-lam

kl_term: 1
kl_beta: 0.01